paginate_per_page: 18
filter:
  Learned: learned
  Not_learned: not_learned
  Alphabet: alphabet
  All: get_all
relationships: ["following", "followers"]
activities:
  followed: followed
  unfollowed: unfollowed
  learned: learned
